name: cemppsa_field_app
description: App de campo CEMPPSA (offline + sync)
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  connectivity_plus: ^6.0.3
  http: ^1.2.2
  provider: ^6.1.5+1
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^3.0.0
